language: python
cache: pip
python:
  - "3.9"
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
before_deploy:
  - gem install dpl
  - gem install faraday -v 1.8.0
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  app: contacteznous
  api_key: $HEROKU_AUTH_TOKEN
  on: 
    repo: Ablayekandji/projetmesurequalitelogiciel
    branch: main